apiVersion: v1
kind: Pod
metadata:
  name: nginredis
  labels:
    app: frontend-backend
spec:
  containers:
  - name: nginx-container
    image: nginx:1.22.1
    ports:
    - containerPort: 80
  - name: redis-container
    image: redis:latest
    ports:
    - containerPort: 6379
