pipeline {
  agent any
    stages {
        stage('Fetch repository') {
            steps {
                sh 'git init'
                sh 'git config core.sparseCheckout true'
                sh 'echo "Homework-19/*" >> .git/info/sparse-checkout'
                sh 'git pull origin master'
            }
        }
        stage('Terraform initialise') {
            steps {
                sh 'terraform init'
            }
        }
    }
}
